# Form implementation generated from reading ui file '.\screens\Login.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 514)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("QWidget {\n"
"    background-color: #F5F6FA;\n"
"    font-family: \"Segoe UI\", \"Roboto\", sans-serif;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_root = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_root.setObjectName("verticalLayout_root")
        spacerItem = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_root.addItem(spacerItem)
        self.horizontalCenterLayout = QtWidgets.QHBoxLayout()
        self.horizontalCenterLayout.setObjectName("horizontalCenterLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalCenterLayout.addItem(spacerItem1)
        self.card = QtWidgets.QFrame(parent=self.centralwidget)
        self.card.setMinimumSize(QtCore.QSize(300, 300))
        self.card.setMaximumSize(QtCore.QSize(350, 400))
        self.card.setStyleSheet("QFrame#card {\n"
"    background-color: white;\n"
"    border-radius: 12px;\n"
"    padding: 20px;\n"
"}")
        self.card.setObjectName("card")
        self.verticalLayout_card = QtWidgets.QVBoxLayout(self.card)
        self.verticalLayout_card.setObjectName("verticalLayout_card")
        self.titleLbl = QtWidgets.QLabel(parent=self.card)
        self.titleLbl.setStyleSheet("font-size: 20px; font-weight: bold; color: #333;")
        self.titleLbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLbl.setObjectName("titleLbl")
        self.verticalLayout_card.addWidget(self.titleLbl)
        self.UserTxt = QtWidgets.QLineEdit(parent=self.card)
        self.UserTxt.setStyleSheet("QLineEdit {\n"
"    background-color: #fff;\n"
"    border: 1px solid #CCC;\n"
"    border-radius: 6px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"}")
        self.UserTxt.setObjectName("UserTxt")
        self.verticalLayout_card.addWidget(self.UserTxt)
        self.PassTxt = QtWidgets.QLineEdit(parent=self.card)
        self.PassTxt.setStyleSheet("QLineEdit {\n"
"    background-color: #fff;\n"
"    border: 1px solid #CCC;\n"
"    border-radius: 6px;\n"
"    padding: 8px;\n"
"    font-size: 14px;\n"
"}")
        self.PassTxt.setObjectName("PassTxt")
        self.verticalLayout_card.addWidget(self.PassTxt)
        self.IngresarBtn = QtWidgets.QPushButton(parent=self.card)
        self.IngresarBtn.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    padding: 8px;\n"
"    border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}")
        self.IngresarBtn.setObjectName("IngresarBtn")
        self.verticalLayout_card.addWidget(self.IngresarBtn)
        self.RegistrarseBtn = QtWidgets.QPushButton(parent=self.card)
        self.RegistrarseBtn.setStyleSheet("QPushButton {\n"
"    background-color: #e0e0e0;\n"
"    color: #333;\n"
"    font-size: 13px;\n"
"    padding: 6px;\n"
"    border-radius: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #d5d5d5;\n"
"}")
        self.RegistrarseBtn.setObjectName("RegistrarseBtn")
        self.verticalLayout_card.addWidget(self.RegistrarseBtn)
        self.horizontalCenterLayout.addWidget(self.card, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalCenterLayout.addItem(spacerItem2)
        self.verticalLayout_root.addLayout(self.horizontalCenterLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_root.addItem(spacerItem3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.titleLbl.setText(_translate("MainWindow", "Iniciar Sesión"))
        self.UserTxt.setPlaceholderText(_translate("MainWindow", "Usuario"))
        self.PassTxt.setPlaceholderText(_translate("MainWindow", "Contraseña"))
        self.IngresarBtn.setText(_translate("MainWindow", "Ingresar"))
        self.RegistrarseBtn.setText(_translate("MainWindow", "Registrarse"))
