# Form implementation generated from reading ui file '.\screens\Main.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class MainWindow_ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #F5F6FA;\n"
"    font-family: \"Segoe UI\", \"Roboto\", sans-serif;\n"
"    font-size: 14px;\n"
"    color: #333;\n"
"}\n"
"\n"
"QLabel {\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    color: #444;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"    padding: 8px 14px;\n"
"    font-size: 14px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #388E3C;\n"
"}\n"
"\n"
"QListView {\n"
"    background-color: #fff;\n"
"    border: 1px solid #CCC;\n"
"    border-radius: 6px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"QListView:focus {\n"
"    border: 1px solid #4CAF50;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.centralLayout.setObjectName("centralLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.centralLayout.addItem(spacerItem)
        self.contentLayout = QtWidgets.QVBoxLayout()
        self.contentLayout.setObjectName("contentLayout")
        self.topRow = QtWidgets.QHBoxLayout()
        self.topRow.setSpacing(16)
        self.topRow.setObjectName("topRow")
        self.saldolbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.saldolbl.setObjectName("saldolbl")
        self.topRow.addWidget(self.saldolbl)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.topRow.addItem(spacerItem1)
        self.CreateBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.CreateBtn.setObjectName("CreateBtn")
        self.topRow.addWidget(self.CreateBtn)
        self.DepositBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.DepositBtn.setObjectName("DepositBtn")
        self.topRow.addWidget(self.DepositBtn)
        self.BuyBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BuyBtn.setObjectName("BuyBtn")
        self.topRow.addWidget(self.BuyBtn)
        self.SellBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SellBtn.setObjectName("SellBtn")
        self.topRow.addWidget(self.SellBtn)
        self.contentLayout.addLayout(self.topRow)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.contentLayout.addItem(spacerItem2)
        self.CryptoList = QtWidgets.QListView(parent=self.centralwidget)
        self.CryptoList.setObjectName("CryptoList")
        self.contentLayout.addWidget(self.CryptoList)
        self.centralLayout.addLayout(self.contentLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.centralLayout.addItem(spacerItem3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.saldolbl.setText(_translate("MainWindow", "Saldo: 0"))
        self.CreateBtn.setText(_translate("MainWindow", "Crear Moneda"))
        self.DepositBtn.setText(_translate("MainWindow", "Depositar"))
        self.BuyBtn.setText(_translate("MainWindow", "Comprar"))
        self.SellBtn.setText(_translate("MainWindow", "Vender"))
