# Form implementation generated from reading ui file '.\screens\Main.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class MainWindow_ui(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QMainWindow {\n"
"        background-color: #f5f5f5; /* Fondo gris muy claro */\n"
"    }\n"
"\n"
"    QLabel {\n"
"        font-size: 14px;\n"
"        font-weight: bold;\n"
"        color: #333;\n"
"    }\n"
"\n"
"    QPushButton {\n"
"        background-color: #4CAF50;   /* Verde agradable */\n"
"        color: white;\n"
"        border-radius: 8px;\n"
"        padding: 8px 16px;\n"
"        font-size: 14px;\n"
"    }\n"
"\n"
"    QPushButton:hover {\n"
"        background-color: #45a049;  /* Verde más oscuro al pasar el mouse */\n"
"    }\n"
"\n"
"    QPushButton:pressed {\n"
"        background-color: #3e8e41;\n"
"    }\n"
"\n"
"    QComboBox {\n"
"        border: 1px solid #aaa;\n"
"        border-radius: 6px;\n"
"        padding: 4px;\n"
"        background-color: white;\n"
"    }")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 110, 341, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saldolbl = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.saldolbl.setObjectName("saldolbl")
        self.horizontalLayout_3.addWidget(self.saldolbl)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.DepositBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.DepositBtn.setObjectName("DepositBtn")
        self.horizontalLayout_3.addWidget(self.DepositBtn)
        self.BuyBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.BuyBtn.setObjectName("BuyBtn")
        self.horizontalLayout_3.addWidget(self.BuyBtn)
        self.SellBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.SellBtn.setObjectName("SellBtn")
        self.horizontalLayout_3.addWidget(self.SellBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.ListComboBox = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.ListComboBox.setObjectName("ListComboBox")
        self.verticalLayout.addWidget(self.ListComboBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.saldolbl.setText(_translate("MainWindow", "Saldo: 0"))
        self.DepositBtn.setText(_translate("MainWindow", "Depositar"))
        self.BuyBtn.setText(_translate("MainWindow", "Comprar"))
        self.SellBtn.setText(_translate("MainWindow", "Vender"))
