# Form implementation generated from reading ui file '.\screens\Register.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(515, 473)
        Dialog.setStyleSheet("QDialog {\n"
"    background-color: #F5F5F5;\n"
"}")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 130, 191, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setStyleSheet("QLabel {\n"
"    font-size: 13px;\n"
"    color: #333333;\n"
"}")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.UserTxt = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.UserTxt.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"}")
        self.UserTxt.setObjectName("UserTxt")
        self.verticalLayout.addWidget(self.UserTxt)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setStyleSheet("QLabel {\n"
"    font-size: 13px;\n"
"    color: #333333;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.PassTxt = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.PassTxt.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid #CCCCCC;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"}")
        self.PassTxt.setObjectName("PassTxt")
        self.verticalLayout.addWidget(self.PassTxt)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.RegistroBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.RegistroBtn.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    padding: 8px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #388E3C;\n"
"}")
        self.RegistroBtn.setObjectName("RegistroBtn")
        self.horizontalLayout.addWidget(self.RegistroBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Cree su usuario"))
        self.label_2.setText(_translate("Dialog", "Cree su contraseña"))
        self.RegistroBtn.setText(_translate("Dialog", "Registrarse"))
